### ISSUE TITLE
the app keep refreshing

### ISSUE THREAD

**Issue by thopah** [JaimeStill/FullstackOverview#1]
the app cann't navigate to Microsoft website process the authentication. Instead, the app keep looping between routes, home and auth/login.

**Comment by JaimeStill** [comment]
Did you setup your own Microsoft app token? See the corresponding [Medium article](https://medium.com/@jpstill85/full-stack-series-stack-demo-e973ac94b1bf)

**Comment by thopah** [comment]
yes, i did setup the Microsoft app token.

**Comment by JaimeStill** [comment]
Without any insight into what steps you took to setup Microsoft authentication as well as a lack of troubleshooting information, there's really nothing you're giving me to go on. Closing this issue until some more tangible details are provided to isolate the issue.
